
 
记录时间：2021-10-09 09:38:37,111 
线程ID:[9] 
日志级别：  INFO  
出错类：LogExcept property: [(null)] - 
错误描述：初始化加载完成
 

 
记录时间：2021-10-09 09:56:17,477 
线程ID:[10] 
日志级别：  INFO  
出错类：LogExcept property: [(null)] - 
错误描述：初始化加载完成
 

 
记录时间：2021-10-09 10:06:18,527 
线程ID:[10] 
日志级别：  INFO  
出错类：LogExcept property: [(null)] - 
错误描述：初始化加载完成
 

 
记录时间：2021-10-09 10:06:31,695 
线程ID:[10] 
日志级别：  DEBUG 
出错类：LogExcept property: [(null)] - 
错误描述：暂停调度器成功
 

 
记录时间：2021-10-09 10:06:32,909 
线程ID:[10] 
日志级别：  DEBUG 
出错类：LogExcept property: [(null)] - 
错误描述：暂停调度器成功
 

 
记录时间：2021-10-09 10:06:33,903 
线程ID:[10] 
日志级别：  DEBUG 
出错类：LogExcept property: [(null)] - 
错误描述：重启调度器成功
 

 
记录时间：2021-10-09 10:06:53,666 
线程ID:[10] 
日志级别：  DEBUG 
出错类：LogExcept property: [(null)] - 
错误描述：控制台日志开启
 

 
记录时间：2021-10-09 10:07:04,339 
线程ID:[10] 
日志级别：  DEBUG 
出错类：LogExcept property: [(null)] - 
错误描述：控制台日志开启
 

 
记录时间：2021-10-09 10:07:29,534 
线程ID:[10] 
日志级别：  DEBUG 
出错类：LogExcept property: [(null)] - 
错误描述：控制台日志开启
 

 
记录时间：2021-10-09 10:07:54,462 
线程ID:[10] 
日志级别：  ERROR 
出错类：LogExcept property: [(null)] - 
错误描述：测试串为空，无法继续
 

 
记录时间：2021-10-09 10:07:57,096 
线程ID:[10] 
日志级别：  ERROR 
出错类：LogExcept property: [(null)] - 
错误描述：测试串为空，无法继续
 

 
记录时间：2021-10-09 10:08:00,687 
线程ID:[10] 
日志级别：  ERROR 
出错类：LogExcept property: [(null)] - 
错误描述：测试串为空，无法继续
 

 
记录时间：2021-10-09 10:08:01,358 
线程ID:[10] 
日志级别：  ERROR 
出错类：LogExcept property: [(null)] - 
错误描述：测试串为空，无法继续
 

 
记录时间：2021-10-09 10:08:01,767 
线程ID:[10] 
日志级别：  ERROR 
出错类：LogExcept property: [(null)] - 
错误描述：测试串为空，无法继续
 

 
记录时间：2021-10-09 10:08:13,748 
线程ID:[10] 
日志级别：  DEBUG 
出错类：LogExcept property: [(null)] - 
错误描述：控制台日志开启
 

 
记录时间：2021-10-09 10:08:18,379 
线程ID:[10] 
日志级别：  DEBUG 
出错类：LogExcept property: [(null)] - 
错误描述：控制台日志开启
 

 
记录时间：2021-10-09 10:08:23,053 
线程ID:[10] 
日志级别：  DEBUG 
出错类：LogExcept property: [(null)] - 
错误描述：控制台日志开启
 

 
记录时间：2021-10-09 10:08:25,637 
线程ID:[10] 
日志级别：  DEBUG 
出错类：LogExcept property: [(null)] - 
错误描述：控制台日志开启
 

 
记录时间：2021-10-09 12:19:58,065 
线程ID:[10] 
日志级别：  INFO  
出错类：LogExcept property: [(null)] - 
错误描述：初始化加载完成
 

 
记录时间：2021-10-09 12:24:55,075 
线程ID:[9] 
日志级别：  INFO  
出错类：LogExcept property: [(null)] - 
错误描述：初始化加载完成
 

 
记录时间：2021-10-09 12:27:43,510 
线程ID:[10] 
日志级别：  INFO  
出错类：LogExcept property: [(null)] - 
错误描述：初始化加载完成
 

 
记录时间：2021-10-09 12:31:33,390 
线程ID:[9] 
日志级别：  INFO  
出错类：LogExcept property: [(null)] - 
错误描述：初始化加载完成
 

 
记录时间：2021-10-09 12:33:49,104 
线程ID:[9] 
日志级别：  INFO  
出错类：LogExcept property: [(null)] - 
错误描述：初始化加载完成
 

 
记录时间：2021-10-09 12:49:35,842 
线程ID:[9] 
日志级别：  INFO  
出错类：LogExcept property: [(null)] - 
错误描述：初始化加载完成
 

 
记录时间：2021-10-09 13:13:19,357 
线程ID:[9] 
日志级别：  INFO  
出错类：LogExcept property: [(null)] - 
错误描述：初始化加载完成
 

 
记录时间：2021-10-09 13:25:11,615 
线程ID:[9] 
日志级别：  INFO  
出错类：LogExcept property: [(null)] - 
错误描述：初始化加载完成
 

 
记录时间：2021-10-09 13:26:40,580 
线程ID:[9] 
日志级别：  INFO  
出错类：LogExcept property: [(null)] - 
错误描述：初始化加载完成
 

 
记录时间：2021-10-09 13:29:05,823 
线程ID:[9] 
日志级别：  DEBUG 
出错类：LogExcept property: [(null)] - 
错误描述：控制台日志开启
 

 
记录时间：2021-10-09 13:29:26,491 
线程ID:[9] 
日志级别：  ERROR 
出错类：LogExcept property: [(null)] - 
错误描述：测试串为空，无法继续
 

 
记录时间：2021-10-09 13:29:29,522 
线程ID:[9] 
日志级别：  ERROR 
出错类：LogExcept property: [(null)] - 
错误描述：测试串为空，无法继续
 

 
记录时间：2021-10-09 13:29:30,169 
线程ID:[9] 
日志级别：  ERROR 
出错类：LogExcept property: [(null)] - 
错误描述：测试串为空，无法继续
 

 
记录时间：2021-10-09 13:29:30,377 
线程ID:[9] 
日志级别：  ERROR 
出错类：LogExcept property: [(null)] - 
错误描述：测试串为空，无法继续
 

 
记录时间：2021-10-09 13:29:30,576 
线程ID:[9] 
日志级别：  ERROR 
出错类：LogExcept property: [(null)] - 
错误描述：测试串为空，无法继续
 

 
记录时间：2021-10-09 13:29:30,752 
线程ID:[9] 
日志级别：  ERROR 
出错类：LogExcept property: [(null)] - 
错误描述：测试串为空，无法继续
 

 
记录时间：2021-10-09 13:31:40,817 
线程ID:[8] 
日志级别：  INFO  
出错类：LogExcept property: [(null)] - 
错误描述：初始化加载完成
 

 
记录时间：2021-10-09 13:32:03,230 
线程ID:[8] 
日志级别：  DEBUG 
出错类：LogExcept property: [(null)] - 
错误描述：控制台日志开启
 

 
记录时间：2021-10-09 13:35:14,477 
线程ID:[9] 
日志级别：  INFO  
出错类：LogExcept property: [(null)] - 
错误描述：初始化加载完成
 

 
记录时间：2021-10-09 13:37:02,735 
线程ID:[9] 
日志级别：  ERROR 
出错类：LogExcept property: [(null)] - 
错误描述：获取作业执行条件异常[RIMS_MZXMLIST]:[RIMS]在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接)
 
System.Data.SqlClient.SqlException (0x80131904): 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接) ---> System.ComponentModel.Win32Exception (0x80004005): 系统找不到指定的文件。
   在 System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   在 System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   在 System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   在 System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   在 Dos.ORM.Database.DoLoadDataSet(DbCommand command, DataSet dataSet, String[] tableNames)
   在 Dos.ORM.Database.LoadDataSet(DbCommand command, DataSet dataSet, String[] tableNames)
   在 Dos.ORM.Database.LoadDataSet(DbCommand command, DataSet dataSet, String tableName)
   在 Dos.ORM.Database.ExecuteDataSet(DbCommand command)
   在 Dos.ORM.DbSession.ExecuteDataSet(DbCommand cmd)
   在 Dos.ORM.Section.ToDataSet()
   在 Dos.ORM.ProcSection.ToDataSet()
   在 Dos.ORM.Section.ToDataTable()
   在 DownLoad.Business.JobInfoManager.GetExcuteCondition(String id, String system) 位置 d:\GitHub\DownLoadExe\DownLoad.Business\JobInfoManager.cs:行号 187
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:2,State:0,Class:20

 
记录时间：2021-10-09 13:37:03,163 
线程ID:[28] 
日志级别：  INFO  
出错类：LogExcept property: [(null)] - 
错误描述：原始数据:{"Request":{"Head":{"Version":"1.1","TranCode":"RIMS_MZXMLIST","TranName":"康复业务-同步门诊项目","TranSys":"RIMS","TranSysName":"康复业务","AckCode":null,"AckMessage":"请求访问","ContentType":"text/json","AppId":"RIMS","MessageId":"437da19e-56dc-4a9e-95c2-9f45b006a9cb"},"Body":""}}
 

 
记录时间：2021-10-09 13:37:36,792 
线程ID:[28] 
日志级别：  ERROR 
出错类：LogExcept property: [(null)] - 
错误描述：【康复业务-同步门诊项目】JkInterfaceBySourceDb执行异常:在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接)
 
System.Data.SqlClient.SqlException (0x80131904): 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接) ---> System.ComponentModel.Win32Exception (0x80004005): 找不到网络路径。
   在 System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   在 System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   在 System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   在 System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   在 Dos.ORM.Database.DoLoadDataSet(DbCommand command, DataSet dataSet, String[] tableNames)
   在 Dos.ORM.Database.LoadDataSet(DbCommand command, DataSet dataSet, String[] tableNames)
   在 Dos.ORM.Database.LoadDataSet(DbCommand command, DataSet dataSet, String tableName)
   在 Dos.ORM.Database.ExecuteDataSet(DbCommand command)
   在 Dos.ORM.DbSession.ExecuteDataSet(DbCommand cmd)
   在 Dos.ORM.Section.ToDataSet()
   在 Dos.ORM.Section.ToDataTable()
   在 DownLoad.Core.GlobalSqlManager.GetDataTable(Int32 dbstyle, String connectstring, String commandsql) 位置 d:\GitHub\DownLoadExe\DownLoad.Core\GlobalSqlManager.cs:行号 48
   在 DownLoad.Business.JkInterfaceBySourceDb.Run(String jobj) 位置 d:\GitHub\DownLoadExe\DownLoad.Business\JkInterfaceBySourceDb.cs:行号 28
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20

 
记录时间：2021-10-09 13:37:36,803 
线程ID:[28] 
日志级别：  ERROR 
出错类：LogExcept property: [(null)] - 
错误描述：返回数据:{"Response":{"Head":{"Version":"1.1","TranCode":"RIMS_MZXMLIST","TranName":"康复业务-同步门诊项目","TranSys":"RIMS","TranSysName":"RIMS","AckCode":"300.1","AckMessage":"在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接)","ContentType":"text/json","AppId":"RIMS","MessageId":"8f817223-5974-4386-87ac-6182a85aef36"},"Body":"[]"}}
 

 
记录时间：2021-10-09 13:38:02,999 
线程ID:[10] 
日志级别：  INFO  
出错类：LogExcept property: [(null)] - 
错误描述：初始化加载完成
 

 
记录时间：2021-10-09 14:45:55,781 
线程ID:[10] 
日志级别：  INFO  
出错类：LogExcept property: [(null)] - 
错误描述：初始化加载完成
 

 
记录时间：2021-10-09 15:47:59,896 
线程ID:[9] 
日志级别：  INFO  
出错类：LogExcept property: [(null)] - 
错误描述：初始化加载完成
 

 
记录时间：2021-10-09 15:51:12,972 
线程ID:[9] 
日志级别：  INFO  
出错类：LogExcept property: [(null)] - 
错误描述：初始化加载完成
 

 
记录时间：2021-10-09 15:51:30,918 
线程ID:[9] 
日志级别：  ERROR 
出错类：LogExcept property: [(null)] - 
错误描述：系统出现未知异常，原因：No default RuleSet is defined for mode definition TSql
 
ICSharpCode.TextEditor.Document.HighlightingDefinitionInvalidException: No default RuleSet is defined for mode definition TSql
   在 ICSharpCode.TextEditor.Document.DefaultHighlightingStrategy.ResolveRuleSetReferences()
   在 ICSharpCode.TextEditor.Document.DefaultHighlightingStrategy.ResolveReferences()
   在 ICSharpCode.TextEditor.Document.HighlightingManager.LoadDefinition(DictionaryEntry entry)
   在 ICSharpCode.TextEditor.Document.HighlightingManager.FindHighlighter(String name)
   在 ICSharpCode.TextEditor.Document.HighlightingStrategyFactory.CreateHighlightingStrategy(String name)
   在 DownLoad.UI.ConfigFrm..ctor(JobInfo info, TreeListNode node, IQuickExcuteInterface Pat) 位置 d:\GitHub\DownLoadExe\DownLoad.UI\ConfigFrm.cs:行号 38
   在 DownLoad.UI.NewMainFrm.WatchConfigFrm() 位置 d:\GitHub\DownLoadExe\DownLoad.UI\NewMainFrm.cs:行号 292
   在 DownLoad.UI.NewMainFrm.treeList1_DoubleClick(Object sender, EventArgs e) 位置 d:\GitHub\DownLoadExe\DownLoad.UI\NewMainFrm.cs:行号 281
   在 System.Windows.Forms.Control.OnDoubleClick(EventArgs e)
   在 DevExpress.XtraTreeList.TreeList.OnDoubleClick(EventArgs e)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 DevExpress.XtraEditors.Container.EditorContainer.WndProc(Message& m)
   在 DevExpress.XtraTreeList.TreeList.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

 
记录时间：2021-10-09 15:56:41,788 
线程ID:[10] 
日志级别：  INFO  
出错类：LogExcept property: [(null)] - 
错误描述：初始化加载完成
 

 
记录时间：2021-10-09 19:05:47,886 
线程ID:[1] 
日志级别：  INFO  
出错类：LogExcept property: [(null)] - 
错误描述：初始化加载完成
 

 
记录时间：2021-10-09 19:06:56,752 
线程ID:[1] 
日志级别：  INFO  
出错类：LogExcept property: [(null)] - 
错误描述：初始化加载完成
 

 
记录时间：2021-10-09 19:20:47,452 
线程ID:[9] 
日志级别：  INFO  
出错类：LogExcept property: [(null)] - 
错误描述：初始化加载完成
 
